### ISSUE TITLE
Feilmelding naar objekt av type SortertEnkelListe opprettes.

### ISSUE THREAD

**Issue by maisongrande** [maisongrande/inf1010OB6#1]
Hei,

Som jeg skrev i commit, faar jeg denne feilmelding under kompilering, men jeg commited noe annet rett etterpaa saa jeg vet ikke om du saa den. Kan hende jeg ikke helt har skjoent hvordan objekter av SortertEnkelListe skal opprettes?

Gir meg uansett for idag, men har du noen ideer er det bare aa si ifra eller endre selv.

./TestSortertEnkelListe.java:4: error: type argument Leger is not within bounds of type-variable T
    SortertEnkelListe<Leger> sel = new SortertEnkelListe<Leger>();
                      ^
  where T is a type-variable:
    T extends Comparable,Lik declared in class SortertEnkelListe
./TestSortertEnkelListe.java:4: error: type argument Leger is not within bounds of type-variable T
    SortertEnkelListe<Leger> sel = new SortertEnkelListe<Leger>();
                                                         ^
  where T is a type-variable:
    T extends Comparable,Lik declared in class SortertEnkelListe
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors

**Comment by maisongrande** [comment]
Løsningen er selvfølgelig at Leger-klassen min mangler Comaparable-implementasjon.

**Comment by krav** [comment]
Ah, la til min lege akkurat siden jeg ikke hadde din, den har nok samme problemet :)

**Comment by maisongrande** [comment]
Tipper det :) Skal få implementert det i Lege i løpet av dagen og se om ikke jeg får skrevet en Test av Listen.

Comparable må tillegges alle klasser som skal kunne puttes i kontainerene regner jeg med, uten at jeg har helt oversikt over hvilke disse er. Skal se på det.. 

Når er nestegang du har mulighet til å treffes?

**Comment by krav** [comment]
Etter to i dag? Jeg reiser til Milano på ettermiddagen. La til resptlistene, skriver tester til dem nå.

**Comment by maisongrande** [comment]
Ja det passer bra, har forelesning frem til da. Kan møtes ved resepsjonen utenfor simula 14ish?
