### ISSUE TITLE
Vaert til inspeksjon

### ISSUE THREAD

**Issue by maisongrande** [maisongrande/inf1010OB6#2]
Hallo Hallo!

Har naa sittet to timer og ventet paa aa faa tilbakemelding.. Fikk kjappe 5 minutter, foer jeg maatte gaa til forelesning.

Tilbakemelding var generelt positiv, men manglende kommentarer og det at Tabell-klassen skriver ut alle elementer fra 0->array.length uten aa sjekke for null-pointer ville han at vi rettet paa. Ellers saa det greit ut (Paapekte sortertEnkelListe algoritmen, men ikke noe krise saa lenge den gjorde det den skulle)

Skal skrive kommentarer i loepet av dagen, saa satser vi paa aa levere i.l.a morgen dagen?

-chris

**Comment by krav** [comment]
Vi har vel litt død kode liggende, får gå over og se hva jeg kan ta bort.
Det er litt for mye å holde styr på.

Kom han med noen tips til sortertenkelliste? Kommer ikke på noen bedre måte
å gjøre det på og det er jo interessant.

2015-03-16 12:13 GMT+01:00 maisongrande notifications@github.com:

> Hallo Hallo!
> 
> Har naa sittet to timer og ventet paa aa faa tilbakemelding.. Fikk kjappe
> 5 minutter, foer jeg maatte gaa til forelesning.
> 
> Tilbakemelding var generelt positiv, men manglende kommentarer og det at
> Tabell-klassen skriver ut alle elementer fra 0->array.length uten aa sjekke
> for null-pointer ville han at vi rettet paa. Ellers saa det greit ut
> (Paapekte sortertEnkelListe algoritmen, men ikke noe krise saa lenge den
> gjorde det den skulle)
> 
> Skal skrive kommentarer i loepet av dagen, saa satser vi paa aa levere
> i.l.a morgen dagen?
> 
> -chris
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/maisongrande/inf1010OB6/issues/2.

## 

Mvh
Kristoffer Ravneberg

**Comment by maisongrande** [comment]
Ja det er veldig mye aa holde styr paa, skal aerlig innroemme at jeg langt ifra har noen form for oversikt.

Skjoenner ikke hva som menes med aa teste for null-peker i tabell sin iterator. Vi fjerner jo aldri et element, saa det vil jo aldri by paa problemer? Eneste er vel hvis arrayet blir fullt, men det er jo en ekstraoppgave hvis man hadde lyst. 

Han sa at det skulle kun vaere noedvendig med test av "mindre enn". Det spiller vel ingen rolle egentlig, men jeg skal se om jeg finner en loesning (Mener jeg har mottat eksempelkode fra gruppelaaerer som viser det, skal lete litt og eventuelt sende deg det) .
Naar det er sagt overhoerte jeg mange kreative loesninger paa SEL, bl.a en gruppe som hadde sortert paa navn-stoerrelse (ant. char i strengen) og de fikk full score...

Er litt i beite paa hva jeg skal ta tak i videre, saa har du noen foeringer paa hva som mangler saa si ifra.

**Comment by maisongrande** [comment]
Fant mailen, sendte deg den paa uio-mail. Skal se ta en titt selv ogsaa.

**Comment by maisongrande** [comment]
Den hjelper jo ikke saa mye da den ikke er generisk..?

**Comment by maisongrande** [comment]
Kan vaere vi gjoer det unoedvindig generisk for oss selv, sakset fra oppgaveteksten:

(...)
Mange av disse beholderene skal kunne brukes til andre formål, men for å ikke gjøre oblig 6 for abstrakt er det kanskje lurt å ha bruken i oblig 7 klart for øyet hele tiden.
(...)
legene skal lagres i et objekt av SortertEnkelListe og personene skal lagres i et objekt av klassen Tabell.

Kan tolkes dit hen det impliseres at vi skal kun ta hensyn til Lege-objekter i ESL

**Comment by krav** [comment]
Tja, jeg kan vel gjøre add(1, null)?

Tror vi skal skrive om SEL#add, men ellers er den grei. Lege er den eneste
typen i hele verden som er både Comparable og Lik.

2015-03-16 18:06 GMT+01:00 maisongrande notifications@github.com:

> Den hjelper jo ikke saa mye da den ikke er generisk..?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/maisongrande/inf1010OB6/issues/2#issuecomment-81812863
> .

## 

Mvh
Kristoffer Ravneberg

**Comment by maisongrande** [comment]
Skrev om add nå på en naiv og lite generisk måte, men har ikke noe bedre forslag til hvordan det kan gjøres.

**Comment by krav** [comment]
Syns det ser fint ut, jeg!

**Comment by maisongrande** [comment]
Da leverer jeg ikveld en gang da, så får vi satt punktum :)

**Comment by krav** [comment]
Bra!

On 17 March 2015 at 15:25, maisongrande notifications@github.com wrote:

> Da leverer jeg ikveld en gang da, så får vi satt punktum :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/maisongrande/inf1010OB6/issues/2#issuecomment-82381465
> .

## 

Mvh
Kristoffer Ravneberg

**Comment by maisongrande** [comment]
Levert...
