### ISSUE TITLE
Naa jobber vi med det samme ser det ut til

### ISSUE THREAD

**Issue by maisongrande** [maisongrande/inf1010OB6#3]
Skulle akkurat pushe Erespt saa ser jeg at du ogsaa har laget en :)
Doepte den til Eresept2, saa kan du ta en titt paa den

**Comment by krav** [comment]
Vi må kanskje koordinere. Min funker, måtte fikse Tabell for å få det til. Eneste forskjellen fra data.txt og det som skrives ut er at vi teller fra 1 på løpenummerene.

Skrev hentResept() og nå tror jeg at jeg gir meg for i dag.

**Comment by maisongrande** [comment]
Bra jobba, medisin til deg!
